const projects = [
  {
    name: "AMDEX 2.0",
    desc: "This is an in-house application designed and built for AMRE Syndicate. It is used as a tool for re-insurance to help track claims and potential losses. Including tracking weather from NOAA data and correlating it with 3,000 points of geographical data for geospatial analysis.",
    img: "amdex2.png",
    live: "x",
    git: "x",
    skills: [
      "React",
      "React Router",
      "Ant Design",
      "amCharts 5",
      "mongoose",
      "MongoDB",
      "Redux",
      "Micorost Azure",
      "Geospatial Analysis",
      "Figma",
      "NOAA APIs",
    ],
  },
  {
    name: "Periodic Tables Restaurant Reservation Manager",
    desc: "This application was made as part of my capstone project for Thinkful Flex Software Engineering course. It is a reservation and table manager to be used by a restaurant that allows for the tracking of reservations as well as seating them to tables and updating their progress. This application was made to meet the specifications laid out by user stories provided by the Thinkful course.",
    img: "preiodic.png",
    live: "https://rrb-uild.vercel.app/",
    git: "https://github.com/okram2k/starter-restaurant-reservation",
    skills: [
      "React",
      "React Router",
      "Bootstrap CSS",
      "Node.js",
      "Knex",
      "PostgreSQL",
    ],
  },
  {
    name: "We Love Movies API",
    desc: "This back-end API was developed to be used by a front-end application to track and display movies, theaters, and reviews of theaters.",
    img: "movies.png",
    live: "x",
    git: "https://github.com/okram2k/We_LoveMovies_1",
    skills: ["JavaScript", "Restful API", "PostgreSQL", "Express", "Node.js"],
  },
  {
    name: "Fro's Flashcard Frenzy",
    desc: "This is the front-end application of a flashcard studying app. Using a provided back-end API the app can list, display, edit, and create study cards and decks of cards. (API currently inactive)",
    img: "flashcard.png",
    live: "https://flashcard-okram2k.vercel.app/",
    git: "https://github.com/okram2k/flashcard",
    skills: [
      "JavaScript",
      "CSS3",
      "HTML5",
      "React",
      "React Routes",
      "React Hooks",
      "Bootstrap",
    ],
  },
  {
    name: "Mini Cactpot Calculator",
    desc: "This simple calculator helps users predict their winnings for a minigame in the MMO Final Fantasy XIV. Using a JavaScript algorithm to keep track of potential winnings on each line and DOM manipulation to track the choices and update other potential choices made by the user.",
    img: "minicactpot.png",
    live: "https://minicactpot.markofithian.repl.co/",
    git: "https://github.com/okram2k/minicactpot",
    skills: ["JavaScript", "DOM", "HTML5"],
  },
  {
    name: "Rolling Run Times Clock",
    desc: "This clock organizes and displays the various run times served by a multi-state operation. The rolling clock displays a countdown to each run time and also considers daylight savings time shifts.",
    img: "clock.png",
    live: "x",
    git: "x",
    skills: ["Microsoft Excel", "VB Scripts"],
  },
  {
    name: "Keep Talking and Nobody Explodes",
    desc: "A real-world implementation of the cooperative video game making a series of puzzles on a real briefcase to be solved before the timer runs out.",
    img: "briefcase.jpg",
    live: "https://drive.google.com/drive/u/0/folders/0B_6MhGUNOywHZ3NnbEJ3Wk84eTA",
    git: "x",
    skills: [
      "C++",
      "PSoC Microprocessor",
      "Custom Printed Circuit Board",
      "Circuit Logic",
      "Team Project Management",
    ],
  },
  {
    name: "Pick and Place Robot",
    desc: "Using an image comparison algorithm to detect the location of a nut placed in the workspace and then instruct a three degree of movement robot to pick up the nut and place it in a designated area.",
    img: "picknplace.jpg",
    live: "x",
    git: "x",
    skills: [
      "MATLAB",
      "C++",
      "PSoC Microprocessor",
      "Custom Printed Circuit Board",
      "Circuit Logic",
    ],
  },
];

export { projects };
